SCR_EditorActionList {
 m_Actions {
  GME_AddGarrisonContextAction "{617456553DC30FA6}" {
   m_Info SCR_UIInfo "{617456555A0E135F}" {
    Name "#GME-ActionList_AddGarrison_Name"
    Description "#GME-ActionList_AddGarrison_Description"
    Icon "{21BAFC03CB14EAD3}UI/Textures/Editor/ContextMenu/ContextAction_BaseSupply.edds"
   }
  }
 }
}